### ISSUE TITLE
Understanding the "kitchen sink" PHP extension

### ISSUE THREAD

**Issue by flexseth** [adamziel/playground-docs-workflow#30]
- [ ] Update docs: Pending PR (mentioned)
- [ ] How to limit the `kitchen sink` - disabling `PHP` extensions or enabling one-by-one...?

## [Getting started with Blueprints](https://wordpress.github.io/wordpress-playground/blueprints-api/index#:~:text=started%20with%20Blueprints-,Getting%20started%20with%20Blueprints,-Blueprints%20are%20JSON)

[Blueprint sample](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#blueprints:~:text=php%22%2C%0A%20%20%20%20%22preferredVersions%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22php%22%3A%20%227.4%22%2C%0A%20%20%20%20%20%20%20%20%22wp%22%3A%20%225.9%22%0A%20%20%20%20%7D%2C-,%22phpExtensionBundles%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22kitchen%2Dsink%22%0A%20%20%20%20%5D%2C,-%22steps%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22step%22%3A%20%22login%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22username%22%3A%20%22admin%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22password)

```JSON
{
    "$schema": "https://playground.wordpress.net/blueprint-schema.json",
    "landingPage": "/wp-admin/",
    "preferredVersions": {
        "php": "8.0",
        "wp": "latest"
    },
    "phpExtensionBundles": ["kitchen-sink"],
    "steps": [
        {
            "step": "login",
            "username": "admin",
            "password": "password"
        }
    ]
}
```

**Comment by flexseth** [comment]
https://wordpress.github.io/wordpress-playground/query-api/
> gd, mbstring, iconv, openssl, libxml, xml, dom, simplexml, xmlreader, xmlwriter

- [ ] **Clarify:** Is this _all_ of the extensions included? 
- [ ] **Discuss:**  Providing a brief explanation and linking out to extension info pages
- [ ] **Drill-down:** Common functionality these extension libraries provide for WordPress
- [ ] **Common errors:** What happens if you don't include a necessary extension? Show codes

## Package explanations
Existing packages that need docs
- `gd`
   - https://github.com/WordPress/wordpress-playground/issues/1190#issuecomment-2034932366
- `mbstring`
- `iconv`
- `openssl`
- `libxml`, `xml`, `simplexml`, `xmlreader`, `xmlwriter`
- `dom`

### To document (new)
`fileInfo` 
- https://github.com/WordPress/wordpress-playground/pull/1179

**Comment by flexseth** [comment]
@adamziel wonders if the `kitchen-sink` "light" option should be by default
- https://github.com/WordPress/wordpress-playground/pull/1191#issuecomment-2035817797

**Comment by flexseth** [comment]
- [ ] Add links to libraries
- [ ] Show a couple of examples of what the libraries do with WordPress
- [ ] How to limit the `kitchen sink`
- [ ] Turn off the `kitchen sink`

Kitchen sink discussion
https://github.com/WordPress/wordpress-playground/pull/1191#issuecomment-2080230179

**Comment by flexseth** [comment]
- [x] Add links to libraries
- [x] Show a couple of examples of what the libraries do with WordPress - unnecessary
- [x] How to limit the `kitchen sink` - mentioned in top-level issue
- [x] Turn off the `kitchen sink` - disabled by default

Kitchen sink discussion
https://github.com/WordPress/wordpress-playground/pull/1191#issuecomment-2080230179

**Comment by adamziel** [comment]
Let’s contain the [docs discussion](https://github.com/WordPress/wordpress-playground/pull/1191#issuecomment-2080230179) in this issue.

> Are there more utilities? In lieu of digging through the repo and trying to figure it out, figured I'd ask here :)

Just those

> Also, are these good representations what the libraries do?

No, these extensions offer many features and can be used in various ways. There’s no need to explain beyond listing them and linking out to php.net. People who need those extensions already know, and there’s no need to rewrite php docs for people who don’t need those extensions yet.

> Are they all PHP extensions?

Yes
