### ISSUE TITLE
wp-now: Error cases for when the user doesn't stop the server

### ISSUE THREAD

**Issue by flexseth** [adamziel/playground-docs-workflow#33]
## Possible error case
User starts the `wp-now` server via
```SHELL
git clone git@github.com:WordPress/playground-tools.git
cd playground-tools
nvm use
npm install
npm run build
nx preview wp-now start --path=/path/to/wordpress-plugin-or-theme
```

Closes VS Code or their editor without stopping the server...

## Discovery
- [X] What happens if the server isn't stopped?
- [X] How to stop the server with Activity Monitor or Task Manager (Windows), Linux

- [X] Server is constantly running in the background?
- [X] What happens if they try to open the VS Code extension in this same folder as `wp-now` is running?

**Comment by ironnysh** [comment]
Hi @flexseth, I've added some clarification below (@adamziel, please correct me if I'm wrong. Don't want to spread misinformation...).

> ## Possible error case
> 
> User starts the `wp-now` server via
> 
> ```SHELL
> 
> git clone git@github.com:WordPress/playground-tools.git
> 
> cd playground-tools
> 
> nvm use
> 
> npm install
> 
> npm run build
> 
> nx preview wp-now start --path=/path/to/wordpress-plugin-or-theme
> 
> ```
> 
These instructions are only relevant [when contributing](https://github.com/WordPress/playground-tools/tree/trunk/packages/wp-now#contributing) to WP-NOW.

> 
> Closes VS Code or their editor without stopping the server...
> 
> ## Discovery
> 
> - [ ] What happens if the server isn't stopped?
> 
Nothing :-) It stops: no Docker involved.

> - [ ] How to stop the server with Activity Monitor or Task Manager (Windows), Linux
> 
You could dig into the specific process in Activity Monitor (under Code/Terminal) and stop it using the UI, but that's both impractical and pointless: once you close the Terminal tab/window (or, in VS Code, for example, either close the window or "Kill" the Terminal), the process shuts down.

> - [ ] Server is constantly running in the background?
> 
Yes, unless you actively stop it (`Control`+`C` or the methods described above).

> - [ ] What happens if they try to open the VS Code extension in this same folder as `wp-now` is running?

It launches the same instance in a new port.

**Comment by flexseth** [comment]
Linking to #31 - Docs for using `wp-now` - some of the quirks about how the server stops, and re-instantiates for sure will be helpful over there. 

@ironnysh - Thanks for your notes above, these are solid. I have a few more notes about how the instance starts based on context I'll link for the `wp-now` docs
