### ISSUE TITLE
reallycoolobjects.com

### ISSUE THREAD

**Issue by flexseth** [adamziel/playground-docs-workflow#55]
**Blueprint idea:** make a website that spoofs the URL bar

User goes to `reallycoolobjects.com` and it looks like their website

Their hosts file is tricked, but it makes demonstration so much better.

## The challenge
> In any case, recreating this huge knowledge base in Playground’s documentation site seems like a bad idea.

Here's a bad idea....

@ironnysh - you're good with `wp-now`  ;)

I've got a scenario for you: 
- create `theme1` folder
- create `theme2` folder
- change localhost settings to spoof `hosts` via a blueprint

The steps should include how to set up VS Code for the instance.

And yes, the user will have to edit their `hosts` file.

## End result
- Playground that spoofs the URL bar so the user sees a "live" site
- Show how to "spoof" a URL in the address bar by editing the `hosts` file 

ie: user's website is called `Really Cool Objects`

the URL bar could show `reallycoolobjects.com`

# Why?
Being able to customize the perceived URL is a huge benefit in many ways.
- Differentiate between live, staging, and development sites
- show something that looks like a "live" site - think new users
- most modern platforms support changing the URL

## Extra Credit
Show how to save developer workspaces in VS Code

Make `theme1` go to `dev.reallycoolobjects.com`

**Comment by ironnysh** [comment]
Hi @flexseth, not sure I follow 😅 Can you elaborate on the _why_?

**Comment by adamziel** [comment]
Also, spoofing the hosts file from Playground isn't technically possible.

**Comment by flexseth** [comment]
I tried getting this to work based on the instructions available in the `wp-now` [documentation](https://www.npmjs.com/package/@wp-now/wp-now#define-custom-urls-in-a-blueprint), did not seem to work.

## Hosts file
```BASH
## Playground ##
http://127.0.0.1:8881   http://myurl.wpnow:8881
```

## blueprint
```JSON
{
	"steps": [
		{
			"step": "defineWpConfigConsts",
			"consts": {
				"WP_HOME": "http://myurl.wpnow:8881",
				"WP_SITEURL": "http://myurl.wpnow:8881"
			},
			"method": "define-before-run"
		}
	]
}
```

## `npx` command
```BASH
npx @wp-now/wp-now start --blueprint=blueprint.json
```

## result
```
This site can’t be reached
Check if there is a typo in myurl.wpnow.
DNS_PROBE_FINISHED_NXDOMAIN
```

## errors
```BASH
errors: 'PHP Warning:  Constant WP_HOME already defined in /var/www/html/wp-config.php on line 2\n' +
      'PHP Warning:  Constant WP_SITEURL already defined in /var/www/html/wp-config.php on line 3\n' +
      'PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-config.php:2) in /var/www/html/wp-login.php on line 504\n' +
```

## notable
I ran this in "WordPress" mode - IE: no files or folders except the `blueprint.json` file.

**Comment by ironnysh** [comment]
Hey @flexseth, the hosts file should look like this (_without_ the protocol and port number):

```
127.0.0.1       myurl.wpnow
```
Can you see if it works?

**Comment by flexseth** [comment]
> Hey @flexseth, the hosts file should look like this (_without_ the protocol and port number):
> 
> ```
> 127.0.0.1       myurl.wpnow
> ```

This works, but throws the error
> Warning: Constant WP_HOME already defined in /var/www/html/wp-config.php on line 2
> Warning: Constant WP_SITEURL already defined in /var/www/html/wp-config.php on line 3

Feel like this has been addressed somewhere. 

I'll mark this as closed, there will probably be a good solution for handling URLs at some point.

**Comment by ironnysh** [comment]
@flexseth, you can try resetting the project ([see `wp-now` README](https://github.com/WordPress/playground-tools/blob/trunk/packages/wp-now/README.md#usage)):
`--reset`

Probably better to open a separate issue in the playground-tools repo, though.
